### ISSUE TITLE
BTM() question

### ISSUE THREAD

**Issue by wanthanaj** [bnosac/BTM#10]
Hi,

I am trying to understand how to use BTM(). 

Could you explain why the 2nd column of the first parameter just is a word (not 2 words)?

According to the definition, the second column is a column called of type character containing the sequence of words occurring within the context identifier.

Thank you

**Comment by jwijffels** [comment]
the first column is the context identifier, e.g. a doc_id, the second column a word, the sequence of words will define the biterms in the data, which is set by argument window in ?BTM. See the NOTE in the documentation of ?BTM indicating how biterms are extracted.

See the example in the help of the ?BTM function
```
library(BTM)
library(udpipe)
data("brussels_reviews_anno", package = "udpipe")
x <- subset(brussels_reviews_anno, language == "nl")
x <- subset(x, xpos %in% c("NN", "NNP", "NNS"))
x <- x[, c("doc_id", "lemma")]
head(x, 30)
        doc_id        lemma
67031 19991431         plek
67040 19991431     centraal
67044 19991431      centrum
67046 19991431      brussel
67049 19991431        adres
67058 19991431      brussel
67066 21054450  appartement
67071 21054450      locatie
67074 21054450  loopafstand
67078 21054450         wijk
67082 21054450 metrostation
67098 21054450        gemak
67104 21054450     perfecte
67105 21054450         plek
67108 21054450     verblijf
67112 21054450      brussel
67117 21054450      contact
67120 21054450   verhuurder
67128 21054450   instructie
67134 21054450      sleutel
67137 22581571      bettina
67139 22581571       collin
67157 22581571     omgeving
67163 22581571      centrum
67165 22581571      brussel
67173 22581571         mens
67181 22581571       bordje
67184 22581571         eten
67194 23542577   verhuurder
67195 23542577      joffrey
```

**Comment by jwijffels** [comment]
Closing, ask further questions on stackoverflow after you've read the docs of the BTM functions https://cran.r-project.org/web/packages/BTM/BTM.pdf and https://github.com/xiaohuiyan/xiaohuiyan.github.io/blob/master/paper/BTM-WWW13.pdf
