### ISSUE TITLE
Support for stochastic divergence minimization

### ISSUE THREAD

**Issue by hans-ekbrand** [bnosac/BTM#11]
Excuse my ignorance, but as far as I understand, this package does not (yet) support the algorithm presented in this paper "[Stochastic Divergence Minimization for Biterm Topic Model](https://arxiv.org/abs/1705.00394)" (2017) by Zhenghang Cui, Issei Sato, Masashi Sugiyama. That feature would be nice to have.

Kind regards,

Hans Ekbrand

**Comment by jwijffels** [comment]
Yes, that is correct, it implements the algorithm explained in this paper from 2013
Xiaohui Yan, Jiafeng Guo, Yanyan Lan, Xueqi Cheng. A Biterm Topic Model For Short Text. WWW2013. https://github.com/xiaohuiyan/xiaohuiyan.github.io/blob/master/paper/BTM-WWW13.pdf
And not the algorithm in another paper you refer to from 2017
Are you planning to implement that algorithm from the paper "Stochastic Divergence Minimization for Biterm Topic Model"?

**Comment by hans-ekbrand** [comment]
I have no such plan, I just wanted to express my interest in that version of BTM.

**Comment by jwijffels** [comment]
Where can one find the code from that paper you refer to?

**Comment by hans-ekbrand** [comment]
There is pseudo-code on page 13 in the article, to get real code I guess one have to contact the authors.

**Comment by jwijffels** [comment]
I'm afraid that without code, this issue will not be solved. I'll close this. If you have code which can be integrated, feel free to reopen the issue.
