### ISSUE TITLE
Get log likelihood for held-out data

### ISSUE THREAD

**Issue by omstuhler** [bnosac/BTM#12]
Hi,

Firstly, thx for this great implementation!

I have a minor question regarding estimating LL for held-out data. I’ve been doing this by running a “fake” model with 1 iteration for the held-out data to get the biterms for this dataset in the right format. Is there a more intuitive way to do this / do you think this way of doing it makes sense? 

Reproducible example of what I mean below:
```R
#Load package
library(BTM)

#Make data
      df = as.data.frame(cbind(c("A", "A", "A", "B", "B", "B", "C",  "C"), 
                          c("t1","t1","t2","t1","t3","t3","t3", "t2")))
      df_train = df[1:6,]
      df_test = df[7:8,]
      
#Run Model
      model_train  <- BTM(df_train, k = 2,  alpha = 50/2, beta = .1, 
                     iter = 20, trace = TRUE, window = 200)
      
#Get biterms for test
      model_test  <- BTM(df_test, k = 2,  alpha = 50/2, beta = .1, 
                    iter = 1, trace = TRUE, window = 200)
      biterms_test = terms(x = model_test, type = "biterms")$biterms[,1:2]
      
#Evaluate Held out LL
      ll = logLik(object = model_train, data = biterms_test)
```

**Comment by jwijffels** [comment]
Good question. 
Currently this seems to be indeed a simple workaround to get the biterms there. There is no other straightforward solution currently implemented in the package.
I should add such a function indeed - seems trivial to implement.

FYI: Code of loglikelihood calculation is this. This also indicates that it is important that all words in your biterms_test should also be in the phi element of model_train

```
> BTM:::logLik.BTM
function(object, data = terms.BTM(object, type = 'biterms')$biterms, ...){
  stopifnot(inherits(data, "data.frame"))
  stopifnot(all(c(data[[1]], data[[2]]) %in% rownames(object$phi)))
  lik <- mapply(w1 = data[[1]], 
                w2 = data[[2]], 
                FUN = function(w1, w2){
                  sum(object$phi[w1, ] * object$phi[w2, ] * object$theta)
                })
  list(likelihood = lik, ll = sum(log(lik)))
}
```

**Comment by omstuhler** [comment]
Thx for the fast response! Yes, it's a very minor issue for sure. 
And thank you for the hint. Indeed all terms must be (though not all biterms obviously).

**Comment by jwijffels** [comment]
Thanks for the suggestion. You are lucky, I was working on this today so it is now implemented if you install from github.
You can now get these as
`biterms_test = terms(x = df_test, type = "biterms", window = 200)`
Please test

**Comment by omstuhler** [comment]
Just tried it. Appears that some tokens get replaced with ```NA``` in the Biterms file. Happy to stick with my workaround for now though.

```R
#Make data
df = as.data.frame(cbind(c("A", "A", "A",  "B",  "B"), 
                         c("t1","t1","t2","t2","t2")))

#New function:
biterms_n = terms(x = df, type = "biterms", window = 99)
biterms_n
```

Besides, I noticed that beta in the ```BTM()``` function defaults to .01 instead of .1 as currently suggested in the Argument section of the vignette. 

This is all very very minor. Just letting you know these small things I notice as I make use of the package. Again, thx for putting this together! Extremely helpful for short text.

**Comment by jwijffels** [comment]
thanks for checking. fixed the NA part, I made an error while implementing
also updated the documentation. default is indeed 0.01
please test

**Comment by omstuhler** [comment]
Works perfectly now! Thx. Sorry took me a while to get back to this.

**Comment by jwijffels** [comment]
Thanks for the check. Closing.
