### ISSUE TITLE
Retrieve doc-term matrix manually

### ISSUE THREAD

**Issue by YixiC94** [bnosac/BTM#13]
Understand that BTM models word co-occurrence on a corpus (global) level, however, do you know if there is a way to calculate the document term matrix manually? I'd like to run a regression on metadata (survey score) using each person's topic distribution. Thanks!

**Comment by jwijffels** [comment]
I don't understand your question. Please rephrase. 
There are 4 functions in the package. Maybe the predict function is what you are looking for or maybe the terms function?

**Comment by YixiC94** [comment]
Sure. My dataframe is consisted of short survey responses and scores for each respondent. I was hoping to predict the score using topics generated. However, I understand that BTM only models topic distribution on corpus level. So was wondering if I may still be able to run document-level topic regression on a Dependent Variable?

**Comment by jwijffels** [comment]
Yes that is possible. Look to the predict function. The package documentation and readme has examples on these

**Comment by jwijffels** [comment]
https://cran.r-project.org/web/packages/BTM/BTM.pdf are the docs

**Comment by YixiC94** [comment]
Thanks, will check out the predict function and see the ways in which it can regress on quantitative data on a doc-level.

**Comment by jwijffels** [comment]
Closing, just use the scores from the predict.BTM function in your regressions.
