### ISSUE TITLE
Where tot find meaning of sum_b, sub_w and mix

### ISSUE THREAD

**Issue by rdatasculptor** [bnosac/BTM#6]
I am not sure if it is worth an issue; if not you can close it immediately.

I am trying to understand how the term probabilities must be used to calculate the topic probabilities. In the package you mention the article about BTM as a reference for the meaning of the prediction types sum_b, sub_w and mix. I had a hard time understanding everything in the article and I haven't managed to find anything that seems to explain these types. Can you please point me in the right direction? Many thanks in advance!

**Comment by jwijffels** [comment]
- **sum_b** is p(z|d) = \sum_b{ p(z|b)p(b|d) } - see formula (3) in the paper at https://github.com/xiaohuiyan/xiaohuiyan.github.io/blob/master/paper/BTM-WWW13.pdf. So summating over the biterms.
- **sub_w** is p(z|d) = \sum_w{ p(z|w)p(w|d) }. So summating over the words 
- **mix** is defined in the code: https://github.com/bnosac/BTM/blob/master/src/infer.cpp#L123  as P(z|d) = P(z) * \mult_w P(w|z)

where d = document, z = topic, w = word, b = biterm
The default **sum_b** is what is shown in the paper (formula (3))

**Comment by rdatasculptor** [comment]
Thank you for this perfect answere!
