### ISSUE TITLE
How to determine number of topics?

### ISSUE THREAD

**Issue by rdatasculptor** [bnosac/BTM#8]
Is there a method that helps to decide what's the best number of topics? In LDA there is `ldatuning`, does in BTM excist something similar?

**Comment by jwijffels** [comment]
No, there does not exist such an R package like ldatuning. 
You can look at the logLikelihood indicating how good a biterm is fitted by the model. (see help of ?logLik.BTM). Other measures (e.g. the ones listed at https://github.com/bnosac/BTM/issues/3) are currently not implemented.

**Comment by rdatasculptor** [comment]
Okay thanks, I will do that.
